language: "php"

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

before_script: 
- "composer require codacy/coverage dev-master --dev"
- "composer install"

script: 
- "phpunit --coverage-clover build/logs/clover.xml"

after_script:
  - CODACY_PROJECT_TOKEN="f1a6f515ca49443f8462ab8712663702" vendor/bin/codacycoverage clover

